const M=[
{c:"set",f:"383",n:"Bornga Beef Lover Set",k:"소고기 세트",p:173,tag:"best",meat:2,serves:"3-4",d:"Premium wagyu short ribs, rib finger meat, oyster blade and chuck roll. The full range of cuts in one order, with corn cheese and two drinks.",dk:"프리미엄 와규 갈빗살, 늑간살, 부채살, 척롤까지. 부위를 한 번에 맛보는 구성이며 콘치즈와 음료 두 잔이 포함됩니다."},
{c:"set",f:"385",n:"Bornga Family Feast",k:"가족 세트",p:289,tag:"best",meat:2,serves:"4-6",d:"Wagyu short ribs, rib finger meat, chuck roll and pork belly, with traditional dishes and cold noodles to finish.",dk:"와규 갈빗살, 늑간살, 척롤에 삼겹살까지. 전통 요리와 냉면으로 마무리하는 구성입니다."},
{c:"set",f:"382",n:"Bornga Favorites Set",k:"인기 세트",p:121,meat:2,serves:"2-3",d:"A curated selection of the favourites: wagyu kkot-sal, finger ribs and woo samgyeop, with corn cheese and a drink.",dk:"인기 부위만 골랐습니다. 와규 꽃살, 늑간살, 우삼겹에 콘치즈와 음료 한 잔."},

{c:"bbq",f:"10093639211873973101129",n:"Snowflake Kkot Sal",k:"눈꽃살",p:54,was:58,g:"160g",meat:1,d:"The highest grade of wagyu short rib on the menu, cut by the chef. Marbling so fine it reads as snowfall.",dk:"매장에서 가장 높은 등급의 와규 갈빗살을 셰프가 직접 손질합니다. 눈이 내린 듯한 마블링이 특징입니다."},
{c:"bbq",f:"2",n:"Wagyu Kkot Sal",k:"꽃살",p:49,g:"160g",meat:1,d:"Kkot-sal is the most tender part of the beef, a premium marbled short rib and Bornga's signature cut.",dk:"꽃살은 소고기에서 가장 부드러운 부위로, 마블링이 고운 프리미엄 갈빗살이자 본가의 대표 메뉴입니다."},
{c:"bbq",f:"115",n:"Wagyu Scotch Fillet",k:"와규 꽃등심",p:48,g:"180g",meat:1,d:"Rich, full-bodied and the most evenly marbled cut on the grill.",dk:"풍미가 진하고 마블링이 가장 고르게 퍼진 부위입니다."},
{c:"bbq",f:"117",n:"Wagyu Yangnyeom Kkot Sal",k:"양념꽃살",p:47,tag:"best",g:"160g",meat:1,d:"The marinated version of kkot-sal, in an exclusive sauce developed by chef Paik Jong-won.",dk:"백종원 대표가 개발한 특제 소스에 재운 양념 꽃살입니다."},
{c:"bbq",f:"296",n:"Marinated Beef Ribs",k:"양념편갈비",p:45,g:"",meat:1,d:"Traditional marinated beef prime rib, sourced from the short plate and butterflied by hand.",dk:"갈비 부위를 손질해 전통 방식으로 재운 양념 편갈비입니다."},
{c:"bbq",f:"144",n:"Wagyu Oyster Blade",k:"부채살",p:44,tag:"best",g:"160g",meat:1,d:"Top blade steak from the chuck, with a line of tendon down the middle that keeps every slice juicy.",dk:"목심에서 나오는 부채살로, 가운데 힘줄이 살아 있어 씹을수록 육즙이 돕니다."},
{c:"bbq",f:"178",n:"Wagyu Chuck Roll 9+",k:"와규척롤 9+",p:42,g:"180g",out:1,meat:1,d:"Marble score 9+, with exceptional marbling and a deep, buttery finish.",dk:"마블링 등급 9+. 입에서 녹는 듯한 진한 풍미가 특징입니다."},
{c:"bbq",f:"182",n:"Marinated LA Galbi",k:"LA양념갈비",p:39,tag:"best",meat:1,d:"Bone-in marinated beef prime ribs in the house sauce, cut across the bone, LA style.",dk:"뼈째 자른 갈비를 본가 특제 양념에 재운 LA식 갈비입니다."},
{c:"bbq",f:"325",n:"Marinated Prawn (8pcs)",k:"새우구이",p:38,meat:1,d:"Premium prawns marinated in the house sauce and grilled in the shell. Contains shellfish.",dk:"껍질째 구워 먹는 특제 양념 새우구이입니다. 갑각류가 들어갑니다."},
{c:"bbq",f:"166",n:"Marinated Wagyu Finger Rib",k:"양념 와규 늑간살",p:37,g:"160g",meat:1,d:"Beef prime ribs with the bones removed, prepared in the house marinade.",dk:"갈비 사이 늑간살의 뼈를 발라내 특제 양념에 재웠습니다."},
{c:"bbq",f:"137",n:"Wagyu Finger Ribs",k:"와규 늑간살",p:35,g:"160g",meat:1,d:"A premium cut from between the beef ribs, chewy and with the most concentrated beef flavour here.",dk:"갈비뼈 사이에서 나오는 부위로, 쫄깃하면서 소고기 맛이 가장 진합니다."},
{c:"bbq",f:"386",n:"Garlic Beef Tongue",k:"마늘우설",p:34,tag:"best",meat:1,d:"Thinly sliced beef tongue marinated in the house garlic sauce.",dk:"얇게 썬 우설을 특제 마늘 소스에 재웠습니다."},
{c:"bbq",f:"158",n:"Marinated Pork Ribs",k:"양념돼지갈비",p:32,meat:1,d:"Pork ribs in Bornga's house sauce. Sweet, savoury, and the easiest thing on the grill to share.",dk:"본가 특제 양념에 재운 돼지갈비입니다. 달짝지근하고 굽기 쉬워 함께 나누기 좋습니다."},
{c:"bbq",f:"118",n:"Thin Sliced Beef Tongue",k:"대패우설",p:31,g:"150g",meat:1,d:"Chewy yet tender, and well known as a delicacy. Grill hot and fast, seconds a side.",dk:"쫄깃하면서도 부드러운 별미입니다. 센 불에 한 면씩 짧게 구워 드세요."},
{c:"bbq",f:"177",n:"Pork Jowl",k:"항정살",p:29,g:"180g",meat:1,d:"A rare delicacy, rich in marbling, with a texture between crisp and tender. Only six pieces per pig.",dk:"돼지 한 마리에 여섯 점만 나오는 특수 부위로, 마블링이 좋고 겉은 바삭 속은 부드럽습니다."},
{c:"bbq",f:"119",n:"Marinated Pork Belly (soy)",k:"간장맛 삼겹살",p:29,g:"200g",meat:1,d:"Marinated in the secret soy sauce, so it caramelises as it grills.",dk:"본가 간장 양념에 재워 구우면 표면이 캐러멜처럼 졸아듭니다."},
{c:"bbq",f:"195",n:"Pork Belly",k:"통삼겹",p:28,g:"200g",meat:1,d:"Juicy, thick-cut pork belly, the classic Korean BBQ order.",dk:"두툼하게 썬 육즙 가득한 삼겹살. 한국식 바비큐의 정석입니다."},
{c:"bbq",f:"1",n:"Woo Samgyeop",k:"우삼겹",p:27,tag:"best",g:"160g",meat:1,d:"Very thinly sliced beef brisket, lightly marinated. The fastest and most forgiving cut on the grill.",dk:"아주 얇게 썬 차돌 부위를 가볍게 양념했습니다. 가장 빨리 익고 실패 없는 부위입니다."},
{c:"bbq",f:"197",n:"Cup Mushrooms",k:"버섯",p:8,v:1,d:"For the grill.",dk:"구이용입니다."},
{c:"bbq",f:"10072",n:"Zucchini",k:"애호박",p:8,v:1,d:"For the grill.",dk:"구이용입니다."},
{c:"bbq",f:"10071",n:"Pumpkin",k:"단호박",p:7,v:1,d:"For the grill.",dk:"구이용입니다."},
{c:"bbq",f:"319",n:"Fresh Wasabi",k:"와사비",p:2.5,v:1,d:"Grated to order.",dk:"주문 즉시 갈아 드립니다."},

{c:"small",f:"10076",n:"Yukhoe Blossom",k:"육회",p:22,d:"Korean-style raw beef tartare, served with fresh pear and sesame.",dk:"신선한 배와 참깨를 곁들인 한국식 육회입니다."},
{c:"small",f:"193",n:"Grilled Corn Cheese",k:"콘치즈",p:17,v:1,d:"Sweet corn and melted cheese, baked in a skillet while you grill.",dk:"달콤한 옥수수와 치즈를 무쇠팬에 구워 냅니다."},
{c:"small",f:"10097639230811431490434",n:"Garlic Butter Scallops",k:"관자 버터구이",p:17,tag:"best",d:"Two scallops seared in garlic butter. Contains shellfish and dairy.",dk:"마늘 버터에 구운 관자 두 점입니다. 갑각류와 유제품이 들어갑니다."},
{c:"small",f:"188",n:"Steamed Egg",k:"계란찜",p:17,v:1,d:"Savoury egg custard with a silky texture and a domed top. Arrives still rising.",dk:"부드럽게 부풀어 오른 계란찜입니다. 나갈 때까지 계속 부풀어 오릅니다."},
{c:"small",f:"10075",n:"Wagyu Tteok-Galbi",k:"떡갈비",p:16,out:1,d:"Four patties of finely minced wagyu blended with the house seasoning.",dk:"곱게 다진 와규에 특제 양념을 더한 떡갈비 네 조각입니다."},

{c:"trad",f:"11",n:"Seafood Pancake",k:"해물파전",p:32,tag:"best",d:"Haemul-pajeon: egg, spring onion and fresh seafood, crisp at the edges. Contains shellfish.",dk:"해물파전입니다. 계란과 쪽파, 신선한 해물을 넣고 가장자리를 바삭하게 부쳤습니다. 갑각류가 들어갑니다."},
{c:"trad",f:"12",n:"Jap Chae",k:"잡채",p:28,tag:"best",d:"Sweet potato noodles stir-fried with vegetables and beef in sesame oil.",dk:"당면을 참기름에 볶아 채소와 소고기를 곁들였습니다."},
{c:"trad",f:"159",n:"Jap Chae (vegetarian)",k:"잡채",p:28,v:1,d:"Glass noodles with stir-fried vegetables, without the beef.",dk:"소고기를 빼고 채소만 볶아 낸 잡채입니다."},
{c:"trad",f:"10100639255217410677952",n:"Gungjung Tteokbokki",k:"궁중떡볶이",p:26,tag:"new",d:"A royal court dish from the Joseon Dynasty. Soy-braised rice cakes with beef and vegetables, no chilli.",dk:"조선 왕실에서 유래한 궁중떡볶이입니다. 간장에 조린 떡에 소고기와 채소를 더했고 맵지 않습니다."},
{c:"trad",f:"387",n:"Traditional Tteokbokki",k:"떡볶이",p:26,d:"Rice cakes in Bornga's signature spicy sauce with fish cake and vegetables.",dk:"본가 특제 고추장 소스에 어묵과 채소를 넣고 볶은 떡볶이입니다."},

{c:"rice",f:"192",n:"Yukhoe Bibimbap",k:"육회비빔밥",p:30,d:"Mixed rice with fresh vegetables and marinated raw beef tartare.",dk:"신선한 채소와 육회를 올린 비빔밥입니다."},
{c:"rice",f:"10084",n:"Bulgogi Hotpot",k:"뚝불",p:27,tag:"new",d:"Thinly sliced beef, glass noodles and vegetables in a sweet broth, served in a hot pot.",dk:"얇게 썬 소고기와 당면, 채소를 달큰한 육수에 끓여 뚝배기째 냅니다."},
{c:"rice",f:"18",n:"Dolsot Bibimbap",k:"돌솥비빔밥",p:25,d:"Mixed rice in a stone bowl, so the base crisps while you eat.",dk:"돌솥에 담아내 먹는 동안 바닥이 노릇하게 눌어붙습니다."},
{c:"rice",f:"186",n:"Dolsot Tofu Bibimbap",k:"두부돌솥비빔밥",p:25,v:1,d:"Stone-bowl mixed rice with tofu and a spread of vegetables.",dk:"두부와 여러 가지 채소를 올린 돌솥비빔밥입니다."},
{c:"rice",f:"122",n:"Suntofu Jjigae",k:"순두부찌개",p:24,d:"A rich, savoury stew with velvety soft tofu and clam. Contains shellfish.",dk:"부드러운 순두부와 바지락을 넣고 진하게 끓인 찌개입니다. 갑각류가 들어갑니다."},
{c:"rice",f:"16",n:"Kimchi Jjigae",k:"김치찌개",p:23,tag:"best",d:"Aged kimchi, pork and tofu, simmered hard. The one to order after the meat.",dk:"묵은지와 돼지고기, 두부를 넣고 푹 끓였습니다. 고기 드신 뒤에 시키기 좋습니다."},
{c:"rice",f:"13",n:"Chadol Duenjang Jjigae",k:"차돌된장찌개",p:23,tag:"best",d:"Soybean paste stew with tender beef brisket.",dk:"차돌박이를 넣어 끓인 된장찌개입니다."},
{c:"rice",f:"19",n:"Bornga Naengmyeon",k:"본가냉면",p:23,d:"Cold buckwheat noodles in a mild beef broth.",dk:"삼삼한 소고기 육수에 메밀 면을 말아 냅니다."},
{c:"rice",f:"21",n:"Spicy Bibim Naengmyeon",k:"비빔냉면",p:23,d:"Cold noodles tossed in chilli paste rather than served in broth.",dk:"육수 대신 고추장 양념에 비벼 먹는 냉면입니다."},
{c:"rice",f:"227",n:"Woosamgyeop Ramen",k:"우삼겹라면",p:19,d:"Spicy ramyeon finished with thin-sliced beef brisket.",dk:"얇게 썬 차돌박이를 올린 얼큰한 라면입니다."},
{c:"rice",f:"56",n:"Rice",k:"밥",p:4,v:1,d:"Steamed short-grain rice.",dk:"갓 지은 쌀밥입니다."},

{c:"bev",f:"391",n:"Grape Ade",k:"포도에이드",p:7.5,was:8.5,tag:"best",v:1},
{c:"bev",f:"10023",n:"Mango Ade",k:"망고에이드",p:7.5,was:8.5,tag:"best",v:1},
{c:"bev",f:"393",n:"Peach Ade",k:"복숭아에이드",p:7.5,was:8.5,tag:"best",v:1},
{c:"bev",f:"10003",n:"Passion Fruit Ade",k:"패션후르츠에이드",p:7.5,was:8.5,v:1},
{c:"bev",f:"10059",n:"Crushed Pear Slushy",k:"배슬러시",p:7.5,was:8.5,v:1},
{c:"bev",f:"10060639198140448745650",n:"Green Plum Tea Slushy",k:"매실슬러시",p:7.5,was:9,v:1},
{c:"bev",f:"124",n:"Aloe",k:"알로에",p:7,v:1},
{c:"bev",f:"74",n:"Milkis",k:"밀키스",p:7,v:1},
{c:"bev",f:"73",n:"Morning Rice",k:"아침햇살",p:7,v:1},
{c:"bev",f:"145",n:"Green Plum",k:"매실",p:7,out:1,v:1},
{c:"bev",f:"390",n:"PUREZZA Sparkling Water 750ml",k:"스파클링워터",p:6,v:1},
{c:"bev",f:"72",n:"Welch's Green Grape",k:"웰치스 청포도",p:6,v:1},
{c:"bev",f:"45",n:"Coke",k:"콜라",p:5,v:1},
{c:"bev",f:"47",n:"Coke Zero",k:"콜라제로",p:5,v:1},
{c:"bev",f:"48",n:"Sprite",k:"스프라이트",p:5,v:1},
{c:"bev",f:"49",n:"Fanta",k:"환타",p:5,v:1},
{c:"bev",f:"69",n:"Cocopalm",k:"코코팜",p:4.5,v:1},
{c:"bev",f:"52",n:"Bong Bong",k:"봉봉",p:4.5,v:1},
{c:"bev",f:"372",n:"Pororo Strawberry",k:"뽀로로 딸기",p:3.5,v:1},
{c:"bev",f:"43",n:"Green Tea (Hot)",k:"녹차",p:3.5,v:1},

{c:"beer",f:"75",n:"Sobee Set",k:"소맥세트",p:49,d:"Soju and beer for the table, with the glasses to build it properly.",dk:"소주와 맥주, 제대로 말아 마실 잔까지 함께 나갑니다."},
{c:"beer",f:"33",n:"Bokbunja",k:"복분자",p:38,out:1,d:"Korean black raspberry wine.",dk:"복분자로 빚은 한국 과실주입니다."},
{c:"beer",f:"31",n:"Original Soju",k:"참이슬",p:22},
{c:"beer",f:"184",n:"Jinro Is Back",k:"진로이즈백",p:22},
{c:"beer",f:"76",n:"Peach Soju",k:"복숭아",p:22},
{c:"beer",f:"64",n:"Green Grape Soju",k:"청포도",p:22},
{c:"beer",f:"376",n:"Lemon Soju",k:"레몬의 이슬",p:22},
{c:"beer",f:"230",n:"Mango Soju",k:"망고",p:22},
{c:"beer",f:"228",n:"Yogurt Soju",k:"요거트",p:22},
{c:"beer",f:"10073",n:"Lychee Soju",k:"리치",p:22},
{c:"beer",f:"10074",n:"Melon Soju",k:"메론",p:22},
{c:"beer",f:"34639252798316140326",n:"Sparkling Makgeoli",k:"생막걸리",p:19,d:"Fresh plain-flavour sparkling rice wine, served cold in a bowl.",dk:"탄산이 살아 있는 생막걸리를 차갑게 사발에 담아 냅니다."},
{c:"beer",f:"155",n:"Peach Makgeoli",k:"복숭아막걸리",p:19},
{c:"beer",f:"183",n:"Chestnut Makgeoli",k:"알밤막걸리",p:19},
{c:"beer",f:"231",n:"Asahi Super Dry 440ml",k:"아사히",p:16},
{c:"beer",f:"232",n:"Bornga Tap Beer 400ml",k:"본가 생맥주",p:15},
{c:"beer",f:"10070",n:"Stone & Wood",k:"스톤앤우드",p:12.5},
{c:"beer",f:"10069",n:"Corona",k:"코로나",p:12,out:1},
{c:"beer",f:"29",n:"Cass",k:"카스",p:11},
{c:"beer",f:"10090639216149675923842",n:"Great Northern Zero",k:"무알콜 맥주",p:10.5},

{c:"wine",f:"10056",n:"Penfolds Bin 28 Shiraz",k:"",p:99},
{c:"wine",f:"300",n:"Yering Station Pinot Noir",k:"",p:65},
{c:"wine",f:"10081",n:"Chandon Brut",k:"",p:65,d:"A perfectly seasoned little sparkling, Chardonnay and Pinot Noir.",dk:"샤르도네와 피노누아를 블렌딩한 균형 잡힌 스파클링입니다."},
{c:"wine",f:"152",n:"Oyster Bay Sauvignon Blanc",k:"",p:55},
{c:"wine",f:"153",n:"Taylors Shiraz, Clare Valley",k:"",p:49},
{c:"wine",f:"39",n:"House Red (glass)",k:"하우스 레드",p:8.5},
{c:"wine",f:"35",n:"House White (glass)",k:"하우스 화이트",p:8.5},

{c:"cock",f:"365",n:"Lemon Highball",k:"레몬 하이볼",p:17,tag:"best"},
{c:"cock",f:"367",n:"Grape Highball",k:"포도 하이볼",p:17,tag:"best"},
{c:"cock",f:"368",n:"Peach Highball",k:"복숭아 하이볼",p:17,tag:"best"},
{c:"cock",f:"379",n:"Passion Fruit Highball",k:"패션후르츠 하이볼",p:17},
{c:"cock",f:"10036",n:"Mango Highball",k:"망고 하이볼",p:17},

{c:"gf",f:"242",n:"Gluten Free Wagyu Kkot Sal",k:"꽃살",p:49,gf:1,meat:1},
{c:"gf",f:"240",n:"Gluten Free Wagyu Scotch Fillet",k:"와규 꽃등심",p:48,gf:1,meat:1},
{c:"gf",f:"245",n:"Gluten Free Wagyu Oyster Blade",k:"부채살",p:44,gf:1,meat:1},
{c:"gf",f:"243",n:"Gluten Free Wagyu Finger Ribs",k:"와규 늑간살",p:35,gf:1,meat:1},
{c:"gf",f:"244",n:"Gluten Free Thin Sliced Beef Tongue",k:"대패우설",p:31,gf:1,meat:1},
{c:"gf",f:"249",n:"Gluten Free Yukhoe Bibimbap",k:"육회비빔밥",p:30,gf:1},
{c:"gf",f:"247",n:"Gluten Free Hang-jeong Sal",k:"항정살",p:29,gf:1,meat:1},
{c:"gf",f:"246",n:"Gluten Free Pork Belly",k:"통삼겹",p:28,gf:1,meat:1},
{c:"gf",f:"250",n:"Gluten Free Dolsot Tofu Bibimbap",k:"두부돌솥비빔밥",p:25,gf:1,v:1},
{c:"gf",f:"248",n:"Gluten Free Yukhoe",k:"육회",p:22,gf:1},
{c:"gf",f:"347",n:"Gluten Free Corn Cheese",k:"콘치즈",p:16,gf:1,v:1},

{c:"take",f:"302",n:"LA Galbi Jeongsik",k:"LA갈비정식",p:36},
{c:"take",f:"304",n:"Seafood Pancake",k:"해물파전",p:32},
{c:"take",f:"305",n:"Jap Chae",k:"잡채",p:28},
{c:"take",f:"303",n:"Pork Galbi Jeongsik",k:"돼지갈비정식",p:27},
{c:"take",f:"308",n:"Traditional Tteokbokki",k:"떡볶이",p:26},
{c:"take",f:"309",n:"Dolsot Bibimbap",k:"돌솥비빔밥",p:25},
{c:"take",f:"314",n:"Suntofu Jjigae",k:"순두부찌개",p:24},
{c:"take",f:"331",n:"Cold Noodle",k:"냉면",p:23},
{c:"take",f:"332",n:"Spicy Cold Noodle",k:"비빔냉면",p:23},
{c:"take",f:"301",n:"Woosamgyeop Jeongsik",k:"우삼겹정식",p:23},
{c:"take",f:"316",n:"Chadol Duenjang Jjigae",k:"차돌된장찌개",p:23},
{c:"take",f:"315",n:"Kimchi Jjigae",k:"김치찌개",p:23},
{c:"take",f:"173",n:"Radish Kimchi 220ml",k:"무생채",p:6,v:1,d:"To take home, by the tub.",dk:"집에서도 드실 수 있도록 통에 담아 드립니다."},
{c:"take",f:"172",n:"Kimchi 220ml",k:"김치",p:6,v:1,d:"To take home, by the tub.",dk:"집에서도 드실 수 있도록 통에 담아 드립니다."},
{c:"take",f:"171",n:"Mashed Potato 220ml",k:"감자샐러드",p:6,v:1,d:"To take home, by the tub.",dk:"집에서도 드실 수 있도록 통에 담아 드립니다."},
{c:"take",f:"170",n:"Garlic Scapes Pickle 220ml",k:"마늘쫑",p:6,v:1,d:"To take home, by the tub.",dk:"집에서도 드실 수 있도록 통에 담아 드립니다."},
{c:"take",f:"354",n:"3 Sidedishes",k:"반찬 3종",p:6,out:1,d:"Kimchi, potato salad and garlic scape.",dk:"김치, 감자샐러드, 마늘쫑 세 가지입니다."}
];
M.forEach((it,i)=>it.id="i"+i);
const CATS=[
 {id:"set",en:"Sets",ko:"세트"},{id:"bbq",en:"Barbeque",ko:"구이"},{id:"small",en:"Starters",ko:"전채"},
 {id:"trad",en:"Traditional",ko:"전통"},{id:"rice",en:"Rice & Noodles",ko:"식사"},{id:"bev",en:"Drinks",ko:"음료"},
 {id:"beer",en:"Beer & Soju",ko:"주류"},{id:"wine",en:"Wine",ko:"와인"},{id:"cock",en:"Cocktail",ko:"칵테일"},
 {id:"gf",en:"Gluten Free",ko:"글루텐프리"},{id:"take",en:"Takeaway",ko:"포장"}
];
const P=id=>"photos/"+id+".jpg";
const byName=n=>M.find(x=>x.n===n);
const money=n=>"$"+n.toFixed(2);
const pct=it=>it.was?Math.round((it.was-it.p)/it.was*100):0;
const UP={meat:["Original Soju","Bornga Tap Beer 400ml","Grilled Corn Cheese","Kimchi Jjigae"],
          food:["Bornga Tap Beer 400ml","Grape Ade","Rice"],
          drink:["Grilled Corn Cheese","Garlic Butter Scallops","Yukhoe Blossom"]};
const upsFor=it=>UP[it.meat?"meat":(["bev","beer","wine","cock"].includes(it.c)?"drink":"food")]
  .map(byName).filter(x=>x&&x.id!==it.id&&!x.out).slice(0,3);
