const M=[
{c:"set",f:"383",n:"Bornga Beef Lover Set",k:"소고기 세트",p:173,tag:"best",meat:2,serves:"3-4",d:"Premium wagyu short ribs, rib finger meat, oyster blade and chuck roll. The full range of cuts in one order, with corn cheese and two drinks."},
{c:"set",f:"385",n:"Bornga Family Feast",k:"가족 세트",p:289,tag:"best",meat:2,serves:"4-6",d:"Wagyu short ribs, rib finger meat, chuck roll and pork belly, with traditional dishes and cold noodles to finish."},
{c:"set",f:"382",n:"Bornga Favorites Set",k:"인기 세트",p:121,meat:2,serves:"2-3",d:"A curated selection of the favourites: wagyu kkot-sal, finger ribs and woo samgyeop, with corn cheese and a drink."},

{c:"bbq",f:"10093639211873973101129",n:"Snowflake Kkot Sal",k:"눈꽃살",p:54,was:58,g:"160g",meat:1,d:"The highest grade of wagyu short rib on the menu, cut by the chef. Marbling so fine it reads as snowfall."},
{c:"bbq",f:"2",n:"Wagyu Kkot Sal",k:"꽃살",p:49,g:"160g",meat:1,d:"Kkot-sal is the most tender part of the beef, a premium marbled short rib and Bornga's signature cut."},
{c:"bbq",f:"115",n:"Wagyu Scotch Fillet",k:"와규 꽃등심",p:48,g:"180g",meat:1,d:"Rich, full-bodied and the most evenly marbled cut on the grill."},
{c:"bbq",f:"117",n:"Wagyu Yangnyeom Kkot Sal",k:"양념꽃살",p:47,tag:"best",g:"160g",meat:1,d:"The marinated version of kkot-sal, in an exclusive sauce developed by chef Paik Jong-won."},
{c:"bbq",f:"296",n:"Marinated Beef Ribs",k:"양념편갈비",p:45,g:"",meat:1,d:"Traditional marinated beef prime rib, sourced from the short plate and butterflied by hand."},
{c:"bbq",f:"144",n:"Wagyu Oyster Blade",k:"부채살",p:44,tag:"best",g:"160g",meat:1,d:"Top blade steak from the chuck, with a line of tendon down the middle that keeps every slice juicy."},
{c:"bbq",f:"178",n:"Wagyu Chuck Roll 9+",k:"와규척롤 9+",p:42,g:"180g",out:1,meat:1,d:"Marble score 9+, with exceptional marbling and a deep, buttery finish."},
{c:"bbq",f:"182",n:"Marinated LA Galbi",k:"LA양념갈비",p:39,tag:"best",meat:1,d:"Bone-in marinated beef prime ribs in the house sauce, cut across the bone, LA style."},
{c:"bbq",f:"325",n:"Marinated Prawn (8pcs)",k:"새우구이",p:38,meat:1,d:"Premium prawns marinated in the house sauce and grilled in the shell. Contains shellfish."},
{c:"bbq",f:"166",n:"Marinated Wagyu Finger Rib",k:"양념 와규 늑간살",p:37,g:"160g",meat:1,d:"Beef prime ribs with the bones removed, prepared in the house marinade."},
{c:"bbq",f:"137",n:"Wagyu Finger Ribs",k:"와규 늑간살",p:35,g:"160g",meat:1,d:"A premium cut from between the beef ribs, chewy and with the most concentrated beef flavour here."},
{c:"bbq",f:"386",n:"Garlic Beef Tongue",k:"마늘우설",p:34,tag:"best",meat:1,d:"Thinly sliced beef tongue marinated in the house garlic sauce."},
{c:"bbq",f:"158",n:"Marinated Pork Ribs",k:"양념돼지갈비",p:32,meat:1,d:"Pork ribs in Bornga's house sauce. Sweet, savoury, and the easiest thing on the grill to share."},
{c:"bbq",f:"118",n:"Thin Sliced Beef Tongue",k:"대패우설",p:31,g:"150g",meat:1,d:"Chewy yet tender, and well known as a delicacy. Grill hot and fast, seconds a side."},
{c:"bbq",f:"177",n:"Pork Jowl",k:"항정살",p:29,g:"180g",meat:1,d:"A rare delicacy, rich in marbling, with a texture between crisp and tender. Only six pieces per pig."},
{c:"bbq",f:"119",n:"Marinated Pork Belly (soy)",k:"간장맛 삼겹살",p:29,g:"200g",meat:1,d:"Marinated in the secret soy sauce, so it caramelises as it grills."},
{c:"bbq",f:"195",n:"Pork Belly",k:"통삼겹",p:28,g:"200g",meat:1,d:"Juicy, thick-cut pork belly, the classic Korean BBQ order."},
{c:"bbq",f:"1",n:"Woo Samgyeop",k:"우삼겹",p:27,tag:"best",g:"160g",meat:1,d:"Very thinly sliced beef brisket, lightly marinated. The fastest and most forgiving cut on the grill."},
{c:"bbq",f:"197",n:"Cup Mushrooms",k:"버섯",p:8,v:1,d:"For the grill."},
{c:"bbq",f:"10072",n:"Zucchini",k:"애호박",p:8,v:1,d:"For the grill."},
{c:"bbq",f:"10071",n:"Pumpkin",k:"단호박",p:7,v:1,d:"For the grill."},
{c:"bbq",f:"319",n:"Fresh Wasabi",k:"와사비",p:2.5,v:1,d:"Grated to order."},

{c:"small",f:"10076",n:"Yukhoe Blossom",k:"육회",p:22,d:"Korean-style raw beef tartare, served with fresh pear and sesame."},
{c:"small",f:"193",n:"Grilled Corn Cheese",k:"콘치즈",p:17,v:1,d:"Sweet corn and melted cheese, baked in a skillet while you grill."},
{c:"small",f:"10097639230811431490434",n:"Garlic Butter Scallops",k:"관자 버터구이",p:17,tag:"best",d:"Two scallops seared in garlic butter. Contains shellfish and dairy."},
{c:"small",f:"188",n:"Steamed Egg",k:"계란찜",p:17,v:1,d:"Savoury egg custard with a silky texture and a domed top. Arrives still rising."},
{c:"small",f:"10075",n:"Wagyu Tteok-Galbi",k:"떡갈비",p:16,out:1,d:"Four patties of finely minced wagyu blended with the house seasoning."},

{c:"trad",f:"11",n:"Seafood Pancake",k:"해물파전",p:32,tag:"best",d:"Haemul-pajeon: egg, spring onion and fresh seafood, crisp at the edges. Contains shellfish."},
{c:"trad",f:"12",n:"Jap Chae",k:"잡채",p:28,tag:"best",d:"Sweet potato noodles stir-fried with vegetables and beef in sesame oil."},
{c:"trad",f:"159",n:"Jap Chae (vegetarian)",k:"잡채",p:28,v:1,d:"Glass noodles with stir-fried vegetables, without the beef."},
{c:"trad",f:"10100639255217410677952",n:"Gungjung Tteokbokki",k:"궁중떡볶이",p:26,tag:"new",d:"A royal court dish from the Joseon Dynasty. Soy-braised rice cakes with beef and vegetables, no chilli."},
{c:"trad",f:"387",n:"Traditional Tteokbokki",k:"떡볶이",p:26,d:"Rice cakes in Bornga's signature spicy sauce with fish cake and vegetables."},

{c:"rice",f:"192",n:"Yukhoe Bibimbap",k:"육회비빔밥",p:30,d:"Mixed rice with fresh vegetables and marinated raw beef tartare."},
{c:"rice",f:"10084",n:"Bulgogi Hotpot",k:"뚝불",p:27,tag:"new",d:"Thinly sliced beef, glass noodles and vegetables in a sweet broth, served in a hot pot."},
{c:"rice",f:"18",n:"Dolsot Bibimbap",k:"돌솥비빔밥",p:25,d:"Mixed rice in a stone bowl, so the base crisps while you eat."},
{c:"rice",f:"186",n:"Dolsot Tofu Bibimbap",k:"두부돌솥비빔밥",p:25,v:1,d:"Stone-bowl mixed rice with tofu and a spread of vegetables."},
{c:"rice",f:"122",n:"Suntofu Jjigae",k:"순두부찌개",p:24,d:"A rich, savoury stew with velvety soft tofu and clam. Contains shellfish."},
{c:"rice",f:"16",n:"Kimchi Jjigae",k:"김치찌개",p:23,tag:"best",d:"Aged kimchi, pork and tofu, simmered hard. The one to order after the meat."},
{c:"rice",f:"13",n:"Chadol Duenjang Jjigae",k:"차돌된장찌개",p:23,tag:"best",d:"Soybean paste stew with tender beef brisket."},
{c:"rice",f:"19",n:"Bornga Naengmyeon",k:"본가냉면",p:23,d:"Cold buckwheat noodles in a mild beef broth."},
{c:"rice",f:"21",n:"Spicy Bibim Naengmyeon",k:"비빔냉면",p:23,d:"Cold noodles tossed in chilli paste rather than served in broth."},
{c:"rice",f:"227",n:"Woosamgyeop Ramen",k:"우삼겹라면",p:19,d:"Spicy ramyeon finished with thin-sliced beef brisket."},
{c:"rice",f:"56",n:"Rice",k:"밥",p:4,v:1,d:"Steamed short-grain rice."},

{c:"bev",f:"391",n:"Grape Ade",k:"포도에이드",p:7.5,was:8.5,tag:"best",v:1},
{c:"bev",f:"10023",n:"Mango Ade",k:"망고에이드",p:7.5,was:8.5,tag:"best",v:1},
{c:"bev",f:"393",n:"Peach Ade",k:"복숭아에이드",p:7.5,was:8.5,tag:"best",v:1},
{c:"bev",f:"10003",n:"Passion Fruit Ade",k:"패션후르츠에이드",p:7.5,was:8.5,v:1},
{c:"bev",f:"10059",n:"Crushed Pear Slushy",k:"배슬러시",p:7.5,was:8.5,v:1},
{c:"bev",f:"10060639198140448745650",n:"Green Plum Tea Slushy",k:"매실슬러시",p:7.5,was:9,v:1},
{c:"bev",f:"124",n:"Aloe",k:"알로에",p:7,v:1},
{c:"bev",f:"74",n:"Milkis",k:"밀키스",p:7,v:1},
{c:"bev",f:"73",n:"Morning Rice",k:"아침햇살",p:7,v:1},
{c:"bev",f:"145",n:"Green Plum",k:"매실",p:7,out:1,v:1},
{c:"bev",f:"390",n:"PUREZZA Sparkling Water 750ml",k:"스파클링워터",p:6,v:1},
{c:"bev",f:"72",n:"Welch's Green Grape",k:"웰치스 청포도",p:6,v:1},
{c:"bev",f:"45",n:"Coke",k:"콜라",p:5,v:1},
{c:"bev",f:"47",n:"Coke Zero",k:"콜라제로",p:5,v:1},
{c:"bev",f:"48",n:"Sprite",k:"스프라이트",p:5,v:1},
{c:"bev",f:"49",n:"Fanta",k:"환타",p:5,v:1},
{c:"bev",f:"69",n:"Cocopalm",k:"코코팜",p:4.5,v:1},
{c:"bev",f:"52",n:"Bong Bong",k:"봉봉",p:4.5,v:1},
{c:"bev",f:"372",n:"Pororo Strawberry",k:"뽀로로 딸기",p:3.5,v:1},
{c:"bev",f:"43",n:"Green Tea (Hot)",k:"녹차",p:3.5,v:1},

{c:"beer",f:"75",n:"Sobee Set",k:"소맥세트",p:49,d:"Soju and beer for the table, with the glasses to build it properly."},
{c:"beer",f:"33",n:"Bokbunja",k:"복분자",p:38,out:1,d:"Korean black raspberry wine."},
{c:"beer",f:"31",n:"Original Soju",k:"참이슬",p:22},
{c:"beer",f:"184",n:"Jinro Is Back",k:"진로이즈백",p:22},
{c:"beer",f:"76",n:"Peach Soju",k:"복숭아",p:22},
{c:"beer",f:"64",n:"Green Grape Soju",k:"청포도",p:22},
{c:"beer",f:"376",n:"Lemon Soju",k:"레몬의 이슬",p:22},
{c:"beer",f:"230",n:"Mango Soju",k:"망고",p:22},
{c:"beer",f:"228",n:"Yogurt Soju",k:"요거트",p:22},
{c:"beer",f:"10073",n:"Lychee Soju",k:"리치",p:22},
{c:"beer",f:"10074",n:"Melon Soju",k:"메론",p:22},
{c:"beer",f:"34639252798316140326",n:"Sparkling Makgeoli",k:"생막걸리",p:19,d:"Fresh plain-flavour sparkling rice wine, served cold in a bowl."},
{c:"beer",f:"155",n:"Peach Makgeoli",k:"복숭아막걸리",p:19},
{c:"beer",f:"183",n:"Chestnut Makgeoli",k:"알밤막걸리",p:19},
{c:"beer",f:"231",n:"Asahi Super Dry 440ml",k:"아사히",p:16},
{c:"beer",f:"232",n:"Bornga Tap Beer 400ml",k:"본가 생맥주",p:15},
{c:"beer",f:"10070",n:"Stone & Wood",k:"스톤앤우드",p:12.5},
{c:"beer",f:"10069",n:"Corona",k:"코로나",p:12,out:1},
{c:"beer",f:"29",n:"Cass",k:"카스",p:11},
{c:"beer",f:"10090639216149675923842",n:"Great Northern Zero",k:"무알콜 맥주",p:10.5},

{c:"wine",f:"10056",n:"Penfolds Bin 28 Shiraz",k:"",p:99},
{c:"wine",f:"300",n:"Yering Station Pinot Noir",k:"",p:65},
{c:"wine",f:"10081",n:"Chandon Brut",k:"",p:65,d:"A perfectly seasoned little sparkling, Chardonnay and Pinot Noir."},
{c:"wine",f:"152",n:"Oyster Bay Sauvignon Blanc",k:"",p:55},
{c:"wine",f:"153",n:"Taylors Shiraz, Clare Valley",k:"",p:49},
{c:"wine",f:"39",n:"House Red (glass)",k:"",p:8.5},
{c:"wine",f:"35",n:"House White (glass)",k:"",p:8.5},

{c:"cock",f:"365",n:"Lemon Highball",k:"레몬 하이볼",p:17,tag:"best"},
{c:"cock",f:"367",n:"Grape Highball",k:"포도 하이볼",p:17,tag:"best"},
{c:"cock",f:"368",n:"Peach Highball",k:"복숭아 하이볼",p:17,tag:"best"},
{c:"cock",f:"379",n:"Passion Fruit Highball",k:"패션후르츠 하이볼",p:17},
{c:"cock",f:"10036",n:"Mango Highball",k:"망고 하이볼",p:17},

{c:"gf",f:"242",n:"Gluten Free Wagyu Kkot Sal",k:"꽃살",p:49,gf:1,meat:1},
{c:"gf",f:"240",n:"Gluten Free Wagyu Scotch Fillet",k:"와규 꽃등심",p:48,gf:1,meat:1},
{c:"gf",f:"245",n:"Gluten Free Wagyu Oyster Blade",k:"부채살",p:44,gf:1,meat:1},
{c:"gf",f:"243",n:"Gluten Free Wagyu Finger Ribs",k:"와규 늑간살",p:35,gf:1,meat:1},
{c:"gf",f:"244",n:"Gluten Free Thin Sliced Beef Tongue",k:"대패우설",p:31,gf:1,meat:1},
{c:"gf",f:"249",n:"Gluten Free Yukhoe Bibimbap",k:"육회비빔밥",p:30,gf:1},
{c:"gf",f:"247",n:"Gluten Free Hang-jeong Sal",k:"항정살",p:29,gf:1,meat:1},
{c:"gf",f:"246",n:"Gluten Free Pork Belly",k:"통삼겹",p:28,gf:1,meat:1},
{c:"gf",f:"250",n:"Gluten Free Dolsot Tofu Bibimbap",k:"두부돌솥비빔밥",p:25,gf:1,v:1},
{c:"gf",f:"248",n:"Gluten Free Yukhoe",k:"육회",p:22,gf:1},
{c:"gf",f:"347",n:"Gluten Free Corn Cheese",k:"콘치즈",p:16,gf:1,v:1},

{c:"take",f:"302",n:"LA Galbi Jeongsik",k:"LA갈비정식",p:36},
{c:"take",f:"304",n:"Seafood Pancake",k:"해물파전",p:32},
{c:"take",f:"305",n:"Jap Chae",k:"잡채",p:28},
{c:"take",f:"303",n:"Pork Galbi Jeongsik",k:"돼지갈비정식",p:27},
{c:"take",f:"308",n:"Traditional Tteokbokki",k:"떡볶이",p:26},
{c:"take",f:"309",n:"Dolsot Bibimbap",k:"돌솥비빔밥",p:25},
{c:"take",f:"314",n:"Suntofu Jjigae",k:"순두부찌개",p:24},
{c:"take",f:"331",n:"Cold Noodle",k:"냉면",p:23},
{c:"take",f:"332",n:"Spicy Cold Noodle",k:"비빔냉면",p:23},
{c:"take",f:"301",n:"Woosamgyeop Jeongsik",k:"우삼겹정식",p:23},
{c:"take",f:"316",n:"Chadol Duenjang Jjigae",k:"차돌된장찌개",p:23},
{c:"take",f:"315",n:"Kimchi Jjigae",k:"김치찌개",p:23},
{c:"take",f:"173",n:"Radish Kimchi 220ml",k:"무생채",p:6,v:1,d:"To take home, by the tub."},
{c:"take",f:"172",n:"Kimchi 220ml",k:"김치",p:6,v:1,d:"To take home, by the tub."},
{c:"take",f:"171",n:"Mashed Potato 220ml",k:"감자샐러드",p:6,v:1,d:"To take home, by the tub."},
{c:"take",f:"170",n:"Garlic Scapes Pickle 220ml",k:"마늘쫑",p:6,v:1,d:"To take home, by the tub."},
{c:"take",f:"354",n:"3 Sidedishes",k:"반찬 3종",p:6,out:1,d:"Kimchi, potato salad and garlic scape."}
];
M.forEach((it,i)=>it.id="i"+i);
const CATS=[
 {id:"set",en:"Sets",ko:"세트"},{id:"bbq",en:"Barbeque",ko:"구이"},{id:"small",en:"Starters",ko:"전채"},
 {id:"trad",en:"Traditional",ko:"전통"},{id:"rice",en:"Rice & Noodles",ko:"식사"},{id:"bev",en:"Drinks",ko:"음료"},
 {id:"beer",en:"Beer & Soju",ko:"주류"},{id:"wine",en:"Wine",ko:"와인"},{id:"cock",en:"Cocktail",ko:"칵테일"},
 {id:"gf",en:"Gluten Free",ko:"글루텐프리"},{id:"take",en:"Takeaway",ko:"포장"}
];
const P=id=>"photos/"+id+".jpg";
const byName=n=>M.find(x=>x.n===n);
const money=n=>"$"+n.toFixed(2);
const pct=it=>it.was?Math.round((it.was-it.p)/it.was*100):0;
const UP={meat:["Original Soju","Bornga Tap Beer 400ml","Grilled Corn Cheese","Kimchi Jjigae"],
          food:["Bornga Tap Beer 400ml","Grape Ade","Rice"],
          drink:["Grilled Corn Cheese","Garlic Butter Scallops","Yukhoe Blossom"]};
const upsFor=it=>UP[it.meat?"meat":(["bev","beer","wine","cock"].includes(it.c)?"drink":"food")]
  .map(byName).filter(x=>x&&x.id!==it.id&&!x.out).slice(0,3);
